---
- name: Install basic packages
  dnf:
    name:
      - git
      - unzip
      - wget
      - lsof
    state: latest

- name: Install Apache and PHP
  dnf:
    name:
      - httpd
      - php
      - php-bcmath
      - php-curl
      - php-zip
      - php-gd
    state: latest

- name: Install Node and npm
  dnf:
    name:
      - nodejs
      - npm
    state: latest

- name: Download Composer installer
  get_url:
    url: https://getcomposer.org/installer
    dest: /tmp/composer-setup.php
    mode: '0755'

- name: Install Composer globally
  shell: php /tmp/composer-setup.php --install-dir=/usr/local/bin --filename=composer
  args:
    creates: /usr/local/bin/composer

